apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sync-gateway
  namespace: couchbase
  labels:
    app: sync-gateway
spec:
  jobLabel: sync-gateway
  selector:
    matchLabels:
      app: sync-gateway
  namespaceSelector:
    matchNames:
      - couchbase
  endpoints:
  - port: http

