apiVersion: v1
kind: Service
metadata:
  name: sync-gateway-exporter
  namespace: couchbase
  labels:
    app: sync-gateway
spec:
  ports:
    - port: 9421
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: sync-gateway
  type: ClusterIP
