version: '3.7'

services:
  # This image of Couchbase Server comes pre-intalled with TravelSample bucket
  # and is preconfigured with a RBAC user for Sync Gateway access
  cb:
    image: connectsv/server:6.0.1-enterprise
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
  # There is nothing custom in this image of Sync Gateway. It is just hosted 
  # in a separate repo
  sgw:
    image: connectsv/sync-gateway:2.5.0-enterprise
    volumes:
    - ./testdata/sync-gateway-config.json:/etc/sync_gateway/sync_gateway.json
    command: -adminInterface :4985 /etc/sync_gateway/sync_gateway.json
    ports:
      - 4984-4985:4984-4985
  # comment sgw above and uncomment this one to serve a fake metrics.json as
  # if it was a live sgw running. useful for testing only.
  # sgw:
  #   image: python:slim-stretch
  #   volumes:
  #     - ./collector/testdata/metrics4.json:/data/_expvar
  #   command: python -m http.server --directory /data 4985
  #   ports:
  #     - 4984-4985:4984-4985
  prometheus:
    image: prom/prometheus
    volumes:
    - ./testdata/prometheus.yml:/etc/prometheus/prometheus.yml
    - ./testdata/rules:/etc/prometheus/rules
    ports:
      - 9090:9090
  exporter:
    image: couchbasesamples/sync-gateway-prometheus-exporter:latest
    #image: sgw-exporter
    build:
      context: .
      dockerfile: build.dockerfile
    command: --log.level=debug --sgw.url=http://sgw:4985
    ports:
      - 9421:9421
  grafana:
    image: grafana/grafana:6.2.0
    volumes:
    - ./grafana/data:/var/lib/grafana
    ports:
    - "3000:3000"

networks:
  default:
    driver: bridge
