version: '3.7'

services:
  cb:
    image: connectsv/server:6.0.1-enterprise
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
  sgw:
    image: connectsv/sync-gateway:2.5.0-enterprise
    volumes:
    - ./testdata/sync-gateway-config.json:/etc/sync_gateway/sync_gateway.json
    command: -adminInterface :4985 /etc/sync_gateway/sync_gateway.json
    ports:
      - 4984-4985:4984-4985
  prometheus:
    image: prom/prometheus
    volumes:
    - ./testdata/prometheus.yml:/etc/prometheus/prometheus.yml
    - ./testdata/rules:/etc/prometheus/rules
    ports:
      - 9090:9090
  exporter:
    image: sgw-exporter
    build:
      context: .
      dockerfile: build.dockerfile
    command: --log.level=debug --sgw.url=http://sgw:4985
    ports:
      - 9421:9421
  grafana:
    image: grafana/grafana:6.2.0
    volumes:
    - ./grafana/data:/var/lib/grafana
    ports:
    - "3000:3000"

networks:
  default:
    driver: bridge
