apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sync-gateway
  namespace: couchbase
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sync-gateway
    spec:
      containers:
        - name: sync-gateway
          image: couchbase/sync-gateway:2.5.0-enterprise
          args: ["/sync-gateway-config/sync-gateway-config.json"]
          volumeMounts:
            - name: sgw-config-volume
              mountPath: /sync-gateway-config
              readOnly: true
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
        - name: exporter
          image: caarlos0/sgw-exporter
          ports:
          - name: http
            containerPort: 9421
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
      volumes:
        - name: sgw-config-volume
          secret:
            secretName: sgw-config

---

apiVersion: v1
kind: Service
metadata:
  name: sync-gateway-exporter
  namespace: couchbase
  labels:
    app: sync-gateway
spec:
  ports:
    - port: 9421
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: sync-gateway
  type: ClusterIP

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sync-gateway
  namespace: couchbase
  labels:
    app: sync-gateway
spec:
  jobLabel: sync-gateway
  selector:
    matchLabels:
      app: sync-gateway
  namespaceSelector:
    matchNames:
      - couchbase
  endpoints:
  - port: http

